global:
   scrape_interval: 15s

scrape_configs:
- job_name: minio-job
  bearer_token: eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9tZXRoZXVzIiwic3ViIjoibWluaW9ycGEiLCJleHAiOjQ4NDgxMDcwMTF9.4ieT-dagU6pCvOd-czCM2awAMTmtnEnfohK_7TnelD8GPzq1zsT0KTzwIVOt31iN1UHtLsSe8ScwEKVmfZfwjA
  metrics_path: /minio/v2/metrics/cluster
  scheme: http
  static_configs:
  - targets: ['127.0.0.1:9000']
rule_files:
- minio-alerting.yml
